name: Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    environment:
      name: prod
      url: https://forum.robsigler.com
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify PR is up-to-date with main
      run: git merge-base --is-ancestor $GITHUB_REF_NAME main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.202
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Deploy
      env:
        PUBLISH_FOLDER: "/var/www/forum-app/bin/Release/net6.0/publish"
      run: |
        dotnet publish --configuration Release --no-restore
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOST }}" >> ~/.ssh/known_hosts
        echo -n "${{ secrets.BASE64_SSH_KEY }}"| base64 --decode >> ~/.ssh/tilde.pem
        chmod 600 ~/.ssh/tilde.pem
        ssh -i ~/.ssh/tilde.pem root@forum.robsigler.com "mkdir -p $PUBLISH_FOLDER"
        rsync -a -e "ssh -i ~/.ssh/tilde.pem" bin/Release/net6.0/publish/ root@forum.robsigler.com:$PUBLISH_FOLDER
        ssh -i ~/.ssh/tilde.pem root@forum.robsigler.com "systemctl restart forum.service"
